# Generated by Django 3.1.7 on 2021-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataacquisitionmethod',
            name='method',
            field=models.CharField(choices=[('OBSERVACION', 'Observación'), ('ENTREVISTA', 'Entrevista'), ('EXPLORACION', 'Exploración Física')], default='1', max_length=50),
        ),
    ]
