# Generated by Django 3.1.7 on 2021-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210420_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodology',
            name='methodology',
            field=models.CharField(choices=[('CEFALOCAUDAL', 'Cefalocaudal'), ('HABITOS', 'Hábitos Externos'), ('PATRONES', 'Por Patrones Funcionales'), ('ANAMNESIS', 'Anamnésis de enfermería'), ('AUSCULTACION', 'Auscultación'), ('PALPACION', 'Palpación'), ('PERCUSION', 'Percursión'), ('INSPECCION', 'Inspección')], default='CEFALOCAUDAL', max_length=255),
        ),
    ]
