# Generated by Django 3.1.7 on 2021-04-20 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210420_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='methodology_progress',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)]),
        ),
    ]
