# Generated by Django 3.1.7 on 2021-04-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_progress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodology',
            name='methodology',
            field=models.CharField(choices=[('PATRONES', 'Patrones funcionales'), ('CEFALOCAUDAL', 'Cefalocaudal'), ('HABITOS', 'Hábitos externos'), ('ANAMNESIS', 'Anamnesis de enfermería'), ('PALPACION', 'Palpación'), ('INSPECCION', 'Inspección')], default='CEFALOCAUDAL', max_length=255),
        ),
    ]
